env:
  browser: true
  es6: true
extends: 'angular'
parserOptions:
  sourceType: module
globals:
    angular: true
plugins:
  - angular
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - 0
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  angular/controller-name:
    - 2
    - '/[A-Z].*Controller$/'
settings:
    angular: 2