image: node:4.6.1
pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  only:
  - lv_ems_214_configFile

  script:
  - npm install -s
  - npm run build
  artifacts:
    paths:
    - public
